### ISSUE TITLE
Add new NLDI sources through pull request.

### ISSUE THREAD

**Issue by dblodgett-usgs** [ACWI-SSWD/nldi-services#134]
Currently, the table of sources is a hand-managed database table. We need to design and implement a pull-request based scheme to allow people to 1) submit new data sources for consideration and 2) automate deployment of an updated data source list.

**Comment by kkehl-usgs** [comment]
This will require changes in nldi-db.  Could I get access to that project?

**Comment by dblodgett-usgs** [comment]
Done

**Comment by kkehl-usgs** [comment]
After discussion with Dave Steinich, it sounds like it will be possible to add a new NDLI source through a pull request.  However, in order to run the crawler for a given source, that is currently a manual job that requires access to the production system.  There is no scheduler currently that automatically goes through the crawler_source table and fires off jobs based on it.

**Comment by dblodgett-usgs** [comment]
Seems fine to me. Just getting things registered through an open process would be a positive move.

**Comment by kkehl-usgs** [comment]
Once this functionality is in place, how do we document it?  Just put a how-to in the README?

**Comment by dblodgett-usgs** [comment]
Yes -- and I can take that on as follow up.

**Comment by kkehl-usgs** [comment]
Okay, so a user can open a pull request by modifying this file:

https://github.com/ACWI-SSWD/nldi-db/tree/master/liquibase/changeLogs/nldi/nldi_data/update_crawler_source/crawler_source.tsv

After that the job for the new or modified crawler source will have to be run manually, as it is currently done for any crawler source.
